function init(self)
	msg.post("#", "windowResized")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("pop") then
		timer.delay(1.5, false, function() go.delete() end)
	elseif message_id == hash("windowResized") then
		msg.post("@render:", "getScale", { sprite = go.get("#sprite", "size"), percent = 3 })
	elseif message_id == hash("returnScale") then
		go.set_scale(message.scale)
	end
end